base_url = "https://dylananthony.com"
title = "Dylan Anthony"
description = "Producing quality software with minimal frustration."

compile_sass = false
minify_html = true
taxonomies = [
    { name = "categories" },
    { name = "tags" },
]

# Enable to use with a JavaScript library
build_search_index = false
ignored_content = ["*.acorn"]

# RSS
generate_feed = true

[markdown]
highlight_code = true
highlight_theme = "css"
[extra]
env = "ZOLA_ENV"

[extra.images]
# Width defined in pixels
max_width = 2500

# Open Graph Protocol objects. See: https://ogp.me/
[extra.ogp]
locale = "en_US"
first_name = "Dylan"
last_name = "Anthony"
gender = "non-binary"
username = "dbanty"
