on: push
jobs:
  prettier:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: "yarn install"

      - name: Prettier
        run: "yarn run prettier . --check"

      - name: ESLint
        run: "yarn run eslint ."
